### ISSUE TITLE
Data in repository is problematic

### ISSUE THREAD

**Issue by johngrimes** [PharmAccess/hdc-furahi#3]
I am having trouble cloning this repository, I think due to the large files that are contained within it.

Perhaps we could look at either removing the files from the repo (including history), or using something like [LFS](https://docs.github.com/en/repositories/working-with-files/managing-large-files/configuring-git-large-file-storage).

**Comment by dkapitan** [comment]
@johngrimes apologies for messing this up. I have just removed all the data, the repo is a lot smaller now (just 10 MB).

I have choosen to use the release functionality from GitHub to share the anonymised data, here is the link for the [Tanzania data](https://github.com/PharmAccess/hdc-furahi/releases/tag/tanzania)
